### ISSUE TITLE
No such file or directory: 'responses/introspection-response-2019_10_20_11_27_53.json

### ISSUE THREAD

**Issue by Jineeshak** [szski/shapeshifter#4]
```python
Traceback (most recent call last):
  File "/usr/local/bin/shifter", line 11, in <module>
    load_entry_point('shifter==0.1', 'console_scripts', 'shifter')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/shifter-0.1-py3.5.egg/shifter.py", line 129, in scan
    with open(filename, mode='wb') as localfile:
FileNotFoundError: [Errno 2] No such file or directory: 'responses/introspection-response-2019_10_20_11_27_53.json'
```

**Comment by Jineeshak** [comment]
`mkdir responses`   ¯\_(ツ)_/¯
