### ISSUE TITLE
Relative Path Error During Scan

### ISSUE THREAD

**Issue by joshbart** [szski/shapeshifter#5]
When installing shapeshifter using `python3 -m pip`, the command `shifter` works regardless of path.  This is illustrated below.
```
vagrant@ubuntu-bionic:~$ shifter --version
shifter, version 1.0
vagrant@ubuntu-bionic:~$
```

However, when running a scan, `shifter` must be run from the root folder of the cloned repository or it errors out.

From the root folder:
```
vagrant@ubuntu-bionic:~/src/shifter$
vagrant@ubuntu-bionic:~/src/shifter$ shifter scan -u https://www.hackerone.com/
[INFO] TESTING FOR CONSOLES AND ENDPOINTS
SCANNING....  [####################################]  100%
| POSSIBLE CONSOLE LOCATED AT: https://www.hackerone.com/
|--------------------------------------------------------| 
vagrant@ubuntu-bionic:~/src/shifter$
```
From my home folder:
```
vagrant@ubuntu-bionic:~$ shifter scan -u https://www.hackerone.com/
[INFO] TESTING FOR CONSOLES AND ENDPOINTS
Traceback (most recent call last):
  File "/usr/local/bin/shifter", line 11, in <module>
    load_entry_point('shifter', 'console_scripts', 'shifter')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vagrant/src/shifter/shifter.py", line 87, in scan
    with open('requests/probe/introspection_get.txt', 'r') as queriesstring:
FileNotFoundError: [Errno 2] No such file or directory: 'requests/probe/introspection_get.txt'
vagrant@ubuntu-bionic:~$
```

From within the repo:
```
vagrant@ubuntu-bionic:~/src/shifter/requests$ shifter scan -u https://www.hackerone.com/
[INFO] TESTING FOR CONSOLES AND ENDPOINTS
Traceback (most recent call last):
  File "/usr/local/bin/shifter", line 11, in <module>
    load_entry_point('shifter', 'console_scripts', 'shifter')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vagrant/src/shifter/shifter.py", line 87, in scan
    with open('requests/probe/introspection_get.txt', 'r') as queriesstring:
FileNotFoundError: [Errno 2] No such file or directory: 'requests/probe/introspection_get.txt'
vagrant@ubuntu-bionic:~/src/shifter/requests$
```

**Comment by joshbart** [comment]
I'd try to fix this myself, but I have zero experience with python.  I may be able to come back to it later and help.

**Comment by Clutchisback1** [comment]
Getting the same thing...tinkering now to see if i can solve this riddle.

**Comment by epi052** [comment]
I believe my pull request fixes this

https://github.com/szski/shapeshifter/pull/3

Give it a shot.

**Comment by joshbart** [comment]
@epi052 I was actually using your pull request when I got the errors above.  Thanks for those updates!  This is similar to the one you fixed, since it's also a relative instead of absolute path reference.  That said, the code looks like it's just opening the file so it can set the variable `queriesstring` equal to the really long query line in [introspection_get.txt](https://github.com/szski/shapeshifter/blob/master/requests/probe/introspection_get.txt), so there may be a way to handle that without opening the file.

**Comment by joshbart** [comment]
Looks like this is fixed by running the docker container made in #6, but that pull request still throws the errors fixed in #3. I'll see if I can find some time to merge those changes in.

**Comment by 1522402210** [comment]
@epi052 @joshbart 
[INFO] TESTING FOR INTROSPECTION
[SUCCESS] INTROSPECTION QUERY EXECUTED
Traceback (most recent call last):
  File "/usr/local/bin/shifter", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/shifter.py", line 129, in scan
    with open(filename, mode='wb') as localfile:
FileNotFoundError: [Errno 2] No such file or directory: 'responses/introspection-response-2020_04_15_18_21_10.json'

**Comment by im23pds** [comment]
{"errors":[{"message":"Query has depth of 13, which exceeds max depth of 5"}]}

**Comment by 1522402210** [comment]
@epi052 hi

error:

[INFO] TESTING FOR INTROSPECTION
[SUCCESS] INTROSPECTION QUERY EXECUTED
[SAVED] SCHEMA SAVED TO: responses/introspection-response-2020_04_10_22_55_08.json
Traceback (most recent call last):
  File "/usr/local/bin/shifter", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/shifter.py", line 133, in scan
    parseIntroResp()
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/shifter.py", line 150, in parseIntroResp
    if schema['data']['__schema']['types'] is not None:
KeyError: 'data'


the responses :
{"errors":[{"message":"Query has depth of 13, which exceeds max depth of 5"}]}
