### ISSUE TITLE
Directory not created + code issue

### ISSUE THREAD

**Issue by earthquake** [szski/shapeshifter#8]
Hi,

I tried to use the tool, which looked promising but it crashed twice during the first and second run. First the introspection file was not created because the responses directory was not there:
```
# shifter scan --url https://xxxx/graphql/2018-04-30 --proxies 127.0.0.1:8080
[INFO] TESTING FOR CONSOLES AND ENDPOINTS
SCANNING....  [####################################]  100%          
| POSSIBLE POST ENDPOINT LOCATED AT: https://xxxx/graphql/2018-04-30
[INFO] TESTING FOR INTROSPECTION
[SUCCESS] INTROSPECTION QUERY EXECUTED
Traceback (most recent call last):
  File "/usr/local/bin/shifter", line 11, in <module>
    load_entry_point('shifter==0.1', 'console_scripts', 'shifter')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 129, in scan
    with open(filename, mode='wb') as localfile:
FileNotFoundError: [Errno 2] No such file or directory: 'responses/introspection-response-2020_08_13_10_41_51.json'
```

After I created the responses directory:

```
# shifter scan --url https://xxxx/graphql/2018-04-30 --proxies 127.0.0.1:8080
[INFO] TESTING FOR CONSOLES AND ENDPOINTS
SCANNING....  [####################################]  100%          
| POSSIBLE POST ENDPOINT LOCATED AT: https://xxxx/graphql/2018-04-30
[INFO] TESTING FOR INTROSPECTION
[SUCCESS] INTROSPECTION QUERY EXECUTED
[SAVED] SCHEMA SAVED TO: responses/introspection-response-2020_08_13_10_43_31.json
Traceback (most recent call last):
  File "/usr/local/bin/shifter", line 11, in <module>
    load_entry_point('shifter==0.1', 'console_scripts', 'shifter')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 133, in scan
    parseIntroResp()
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 162, in parseIntroResp
    createQuery(field['name'], arg['name'], arg['type']['name'])
  File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 253, in createQuery
    writeFile("Queries", scalar, field_name+"-"+arg_name, query) 
UnboundLocalError: local variable 'query' referenced before assignment

Unfortunately I am unable to share the introspection file.
```

**Comment by vyastj** [comment]
> Hi,
> 
> I tried to use the tool, which looked promising but it crashed twice during the first and second run. First the introspection file was not created because the responses directory was not there:
> 
> ```
> # shifter scan --url https://xxxx/graphql/2018-04-30 --proxies 127.0.0.1:8080
> [INFO] TESTING FOR CONSOLES AND ENDPOINTS
> SCANNING....  [####################################]  100%          
> | POSSIBLE POST ENDPOINT LOCATED AT: https://xxxx/graphql/2018-04-30
> [INFO] TESTING FOR INTROSPECTION
> [SUCCESS] INTROSPECTION QUERY EXECUTED
> Traceback (most recent call last):
>   File "/usr/local/bin/shifter", line 11, in <module>
>     load_entry_point('shifter==0.1', 'console_scripts', 'shifter')()
>   File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 129, in scan
>     with open(filename, mode='wb') as localfile:
> FileNotFoundError: [Errno 2] No such file or directory: 'responses/introspection-response-2020_08_13_10_41_51.json'
> ```
> 
> After I created the responses directory:
> 
> ```
> # shifter scan --url https://xxxx/graphql/2018-04-30 --proxies 127.0.0.1:8080
> [INFO] TESTING FOR CONSOLES AND ENDPOINTS
> SCANNING....  [####################################]  100%          
> | POSSIBLE POST ENDPOINT LOCATED AT: https://xxxx/graphql/2018-04-30
> [INFO] TESTING FOR INTROSPECTION
> [SUCCESS] INTROSPECTION QUERY EXECUTED
> [SAVED] SCHEMA SAVED TO: responses/introspection-response-2020_08_13_10_43_31.json
> Traceback (most recent call last):
>   File "/usr/local/bin/shifter", line 11, in <module>
>     load_entry_point('shifter==0.1', 'console_scripts', 'shifter')()
>   File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 133, in scan
>     parseIntroResp()
>   File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 162, in parseIntroResp
>     createQuery(field['name'], arg['name'], arg['type']['name'])
>   File "/usr/local/lib/python3.8/dist-packages/shifter-0.1-py3.8.egg/shifter.py", line 253, in createQuery
>     writeFile("Queries", scalar, field_name+"-"+arg_name, query) 
> UnboundLocalError: local variable 'query' referenced before assignment
> 
> Unfortunately I am unable to share the introspection file.
> ```

I am facing this issue as well. The only different thing I did is not to pass through a proxy but simply `shifter scan -u http://localhost:4000/graphql`. However, after I created the `responses` folder. It gave me
```
[INFO] TESTING FOR CONSOLES AND ENDPOINTS
SCANNING....  [####################################]  100%
| POSSIBLE POST ENDPOINT LOCATED AT: http://localhost:4000/graphql
[INFO] TESTING FOR INTROSPECTION
[SUCCESS] INTROSPECTION QUERY EXECUTED
[SAVED] SCHEMA SAVED TO: responses/introspection-response-2020_10_01_12_39_55.json
| Request written to: Queries/user-id-String.json
| Request written to: Queries/company-id-String.json
| Request written to: Queries/addUser-companyId-String.json
| Request written to: Queries/editUser-age-Int.json
| Request written to: Queries/editUser-firstName-String.json
| Request written to: Queries/editUser-companyId-String.json
| Request written to: Queries/fields-includeDeprecated-Boolean.json
| Request written to: Queries/enumValues-includeDeprecated-Boolean.json
[QUERY FAILED] ATTEMPTING SHAPE SHIFT AND RETRYING...
[QUERY FAILED] ATTEMPTING SHAPE SHIFT AND RETRYING...
[QUERY FAILED] ATTEMPTING SHAPE SHIFT AND RETRYING...
[QUERY FAILED] ATTEMPTING SHAPE SHIFT AND RETRYING...
```

**Comment by BRANOPODCAST** [comment]
same issue for me
